package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;

import gui.ViewG;
import controller.ControllerServer;

public class ViewPanel extends JFrame implements ViewG{
	ControllerServer control;
    /**
     * Creates new form ViewPanel
     */
    public ViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScroll = new javax.swing.JScrollPane();
        jTextA = new javax.swing.JTextArea();
        jLabelTextoAEnviar = new javax.swing.JLabel();
        jTextFS = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextA.setBackground(new java.awt.Color(153, 153, 153));
        jTextA.setColumns(20);
        jTextA.setRows(5);
        jScroll.setViewportView(jTextA);

        jLabelTextoAEnviar.setText("Texto a Enviar:");

        jButton.setText("Enviar");
        jButton.setEnabled(false);
        jLabelTextoAEnviar.setEnabled(false);
       
        
        jButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				String m = jTextFS.getText();
				if(m!= null) {
				control.finishClientConnection(m);
				}
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTextoAEnviar)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFS))
                            .addComponent(jScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoAEnviar)
                    .addComponent(jTextFS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabelTextoAEnviar;
    private javax.swing.JScrollPane jScroll;
    private javax.swing.JTextArea jTextA;
    private javax.swing.JTextField jTextFS;
    // End of variables declaration//GEN-END:variables

    @Override
    public void enableSend() {
        jButton.setEnabled(true);
    }

    @Override
    public void disableSend() {
        jButton.setEnabled(false);
    }

    @Override
    public void addMessage(String mensaje) {
        jTextA.append(mensaje + "\n");
    }



    @Override
    public void setController(ControllerServer control) {
        this.control = control;
    }

    @Override
    public void makeVisible() {
        setVisible(true);
    }
    
    public void inicialize(){
        jButton.setActionCommand(SEND);
        jButton.addActionListener(control);
    }
    
    @Override
    public String getFieldText() {
    	return jTextFS.getText();
    }
    
    


}

