server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
  endpoint:
    env:
      enabled: true
      
    health:
      enabled: true
      
    info:
      enabled: true
      
    prometheus:
      enabled: true
  metrics:
    export:
      appoptics:
        connect-timeout: 100
    
    
    
      
    
 
     
     
 
  